[project]
name = "voice-infer-stack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "opentelemetry-exporter-otlp-proto-http>=1.44.0",
    "pipecat-ai[kokoro,local-smart-turn,mlx-whisper,silero,tracing,whisper]==1.8.1",
    "soundfile>=0.14.0",
    "transformers>=4.48,<5",
]
